region_name = "eu-west-1"
bucket_name = "markflanagan.org"
lambda_name = "VisitorCounterUpdater"
api_name = "VisitorCounterUpdaterAPI"
dynamodb_name = "SiteVisits"
domain_name = "markflanagan.org"
api_resource_name = "update-count"