name: Frontend Deployment

on:
  push:
    paths:
      - "frontend/**"

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_region }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
            terraform_version: 1.10.0
  
      - name: Initialise Terraform
        working-directory: ./terraform
        run: terraform init

      - name: Test terraform outputs
        working-directory: ./terraform
        run: terraform output

      - name: Get API URL
        id: get_api_url
        run: echo "::set-output name=invoke_url::$(terraform output -raw api_invoke_url)"

      - name: Insert url into JS
        run: |
          sed -i 's|<API_GATEWAY_URL>|${{ steps.get_api_url.outputs.invoke_url }}|g' ./frontend/scripts/LambdaCaller.js

      - name: Sync JS to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          
        run: |
          aws s3 sync ./frontend/ s3://markflanagan.org