name: Infrastructure Deployment

on:
  push:
    paths:
      - 'terraform/**'

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.10.0

      - name: Initialise Terraform
        run: terraform init

      - name: Get Table Name
        id: get_dynamodb_table
        run: echo "DYNAMODB_TABLE_NAME=$(terraform output -raw dynamodb_table)" >> $GITHUB_ENV

      - name: Check output
        run: echo "Table Name ${{ env.DYNAMODB_TABLE_NAME }}"

      - name: Validate Terraform
        run: terraform validate

      - name: Plan Terraform
        run: terraform plan

      - name: Apply Terraform
        if: github.event_name == 'push'
        run: terraform apply -auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}