name: Lambda Deployment

on:
  push:
    paths:
      - "backend/**"

jobs:
  deploy-lambda:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Zip Lambda function
        run: zip -r -j function.zip ./backend/lambda_function.py

      - name: Deploy Lambda function
        run: |
          aws lambda update-function-code \
            --region eu-west-1 \
            --function-name VisitorCounterUpdater \
            --zip-file fileb://function.zip

        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}